# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'massage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(338, 132)
        Dialog.setStyleSheet("QDialog{background: transparent;}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setStyleSheet("QGroupBox{margin-top:0;background-color:#ffffff;color: #ffffff;border-radius:5px;}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.groupBox)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.massage = QtWidgets.QLabel(self.groupBox)
        self.massage.setObjectName("massage")
        self.verticalLayout.addWidget(self.massage)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nobtn = QtWidgets.QPushButton(self.groupBox)
        self.nobtn.setMinimumSize(QtCore.QSize(0, 30))
        self.nobtn.setStyleSheet("QPushButton {\n"
"border-radius:5px;\n"
"border:1px solid #e6e6e6;\n"
"background-color: #ffffff;\n"
"color: #4683ff;\n"
"font-family:Roboto, \'Segoe UI\', Tahoma, sans-serif;\n"
"padding-left:15px;\n"
"padding-right:15px;}\n"
"QPushButton::hover {background-color:#ecf2ff;}")
        self.nobtn.setObjectName("nobtn")
        self.horizontalLayout_2.addWidget(self.nobtn)
        self.okbtn = QtWidgets.QPushButton(self.groupBox)
        self.okbtn.setMinimumSize(QtCore.QSize(0, 30))
        self.okbtn.setStyleSheet("QPushButton {\n"
"border-radius:5px;\n"
"background-color: #4683ff;\n"
"color: #ffffff;\n"
"font-family:Roboto, \'Segoe UI\', Tahoma, sans-serif;\n"
"padding-left:15px;\n"
"padding-right:15px;}\n"
"QPushButton::hover {background-color:#568dff;}")
        self.okbtn.setObjectName("okbtn")
        self.horizontalLayout_2.addWidget(self.okbtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title.setText(_translate("Dialog", "TextLabel"))
        self.massage.setText(_translate("Dialog", "TextLabel"))
        self.nobtn.setText(_translate("Dialog", "لا"))
        self.okbtn.setText(_translate("Dialog", "نعم"))
