# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patientlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(295, 73)
        Form.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sora = QtWidgets.QLabel(self.groupBox)
        self.sora.setMinimumSize(QtCore.QSize(50, 50))
        self.sora.setMaximumSize(QtCore.QSize(50, 50))
        self.sora.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sora.setText("")
        self.sora.setPixmap(QtGui.QPixmap(":/MainSources/youthMale.png"))
        self.sora.setObjectName("sora")
        self.horizontalLayout_2.addWidget(self.sora)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tasjeel = QtWidgets.QLabel(self.groupBox)
        self.tasjeel.setStyleSheet("QLabel{color:#a6a9b6;}")
        self.tasjeel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tasjeel.setObjectName("tasjeel")
        self.verticalLayout.addWidget(self.tasjeel)
        self.patName = QtWidgets.QLabel(self.groupBox)
        self.patName.setMaximumSize(QtCore.QSize(150, 16777215))
        self.patName.setStyleSheet("QLabel{color:#4683ff;}")
        self.patName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.patName.setObjectName("patName")
        self.verticalLayout.addWidget(self.patName)
        self.patInfo = QtWidgets.QLabel(self.groupBox)
        self.patInfo.setStyleSheet("QLabel{color:#a6a9b6;}")
        self.patInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.patInfo.setObjectName("patInfo")
        self.verticalLayout.addWidget(self.patInfo)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tasjeel.setText(_translate("Form", "TextLabel"))
        self.patName.setText(_translate("Form", "TextLabel"))
        self.patInfo.setText(_translate("Form", "TextLabel"))
import sources_rc
