# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'priceEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 224)
        Dialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        Dialog.setStyleSheet("QDialog{background: transparent;}\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setStyleSheet("QGroupBox{color: rgb(0, 170, 255);background-color: #fcfcfc;border-radius:5px;}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox{color: rgb(0, 170, 255);background-color: rgb(255, 255, 255);border-radius:5px;}")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plana = QtWidgets.QLineEdit(self.groupBox)
        self.plana.setAlignment(QtCore.Qt.AlignCenter)
        self.plana.setObjectName("plana")
        self.horizontalLayout_2.addWidget(self.plana)
        self.planb = QtWidgets.QLineEdit(self.groupBox)
        self.planb.setAlignment(QtCore.Qt.AlignCenter)
        self.planb.setObjectName("planb")
        self.horizontalLayout_2.addWidget(self.planb)
        self.planc = QtWidgets.QLineEdit(self.groupBox)
        self.planc.setAlignment(QtCore.Qt.AlignCenter)
        self.planc.setObjectName("planc")
        self.horizontalLayout_2.addWidget(self.planc)
        self.pland = QtWidgets.QLineEdit(self.groupBox)
        self.pland.setAlignment(QtCore.Qt.AlignCenter)
        self.pland.setObjectName("pland")
        self.horizontalLayout_2.addWidget(self.pland)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox{color: rgb(0, 170, 255);background-color: rgb(255, 255, 255);border-radius:5px;}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.planaa = QtWidgets.QLineEdit(self.groupBox_2)
        self.planaa.setAlignment(QtCore.Qt.AlignCenter)
        self.planaa.setObjectName("planaa")
        self.horizontalLayout_4.addWidget(self.planaa)
        self.planbb = QtWidgets.QLineEdit(self.groupBox_2)
        self.planbb.setAlignment(QtCore.Qt.AlignCenter)
        self.planbb.setObjectName("planbb")
        self.horizontalLayout_4.addWidget(self.planbb)
        self.plancc = QtWidgets.QLineEdit(self.groupBox_2)
        self.plancc.setAlignment(QtCore.Qt.AlignCenter)
        self.plancc.setObjectName("plancc")
        self.horizontalLayout_4.addWidget(self.plancc)
        self.plandd = QtWidgets.QLineEdit(self.groupBox_2)
        self.plandd.setAlignment(QtCore.Qt.AlignCenter)
        self.plandd.setObjectName("plandd")
        self.horizontalLayout_4.addWidget(self.plandd)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.saveprices = QtWidgets.QPushButton(self.groupBox_3)
        self.saveprices.setStyleSheet("QPushButton{background-color:#0FA6F5;\n"
"height:20px;\n"
"width:60px;\n"
"padding:3px;\n"
"border: 2px;\n"
"color:white;\n"
"border-style: outset;\n"
"border-color: #035aa6;\n"
"border-radius: 3px;}\n"
"QPushButton::hover{\n"
"background-color:white;\n"
"width:50px;\n"
"padding:3px;\n"
"border: 2px;\n"
"color:#035aa6;\n"
"border-style: inset;\n"
"border-color: #0FA6F5;\n"
"border-radius: 3px;\n"
"}")
        self.saveprices.setObjectName("saveprices")
        self.horizontalLayout_5.addWidget(self.saveprices)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setStyleSheet("QPushButton{background-color:#0FA6F5;\n"
"height:20px;\n"
"width:60px;\n"
"padding:3px;\n"
"border: 2px;\n"
"color:white;\n"
"border-style: outset;\n"
"border-color: #035aa6;\n"
"border-radius: 3px;}\n"
"QPushButton::hover{\n"
"background-color:white;\n"
"width:50px;\n"
"padding:3px;\n"
"border: 2px;\n"
"color:#035aa6;\n"
"border-style: inset;\n"
"border-color: #0FA6F5;\n"
"border-radius: 3px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.groupBox_3)

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "خطة أسعار الكشف"))
        self.label.setText(_translate("Dialog", "خطة A"))
        self.label_4.setText(_translate("Dialog", "خطة B"))
        self.label_3.setText(_translate("Dialog", "خطة C"))
        self.label_2.setText(_translate("Dialog", "خطة D"))
        self.groupBox_2.setTitle(_translate("Dialog", "خطة أسعار الإستشارة"))
        self.label_7.setText(_translate("Dialog", "خطة A"))
        self.label_8.setText(_translate("Dialog", "خطة B"))
        self.label_6.setText(_translate("Dialog", "خطة C"))
        self.label_5.setText(_translate("Dialog", "خطة D"))
        self.saveprices.setText(_translate("Dialog", "حفظ"))
        self.pushButton.setText(_translate("Dialog", "إلغاء"))
