# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'printPreview.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1002, 638)
        Dialog.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dialogbox = QtWidgets.QGroupBox(Dialog)
        self.dialogbox.setStyleSheet("QGroupBox{border: 1px solid palette(dark);}")
        self.dialogbox.setTitle("")
        self.dialogbox.setObjectName("dialogbox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dialogbox)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainwin = QtWidgets.QGroupBox(self.dialogbox)
        self.mainwin.setStyleSheet("QGroupBox{border:0;background-color: #cdd0cb;}")
        self.mainwin.setTitle("")
        self.mainwin.setAlignment(QtCore.Qt.AlignCenter)
        self.mainwin.setObjectName("mainwin")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainwin)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.group = QtWidgets.QGroupBox(self.mainwin)
        self.group.setStyleSheet("QGroupBox{background-color: transparent;}\n"
"QLabel{background-color:transparent;}")
        self.group.setTitle("")
        self.group.setObjectName("group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.group)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label5 = QtWidgets.QLabel(self.group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label5.sizePolicy().hasHeightForWidth())
        self.label5.setSizePolicy(sizePolicy)
        self.label5.setMinimumSize(QtCore.QSize(560, 560))
        self.label5.setMaximumSize(QtCore.QSize(560, 560))
        self.label5.setStyleSheet("QLabel{background-color:transparent;}")
        self.label5.setAlignment(QtCore.Qt.AlignCenter)
        self.label5.setObjectName("label5")
        self.verticalLayout_3.addWidget(self.label5)
        self.horizontalLayout_3.addWidget(self.group)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.urllocation = QtWidgets.QLineEdit(self.mainwin)
        self.urllocation.setStyleSheet("QLineEdit{border: 1px;border-style: solid;border-color: rgb(194, 194, 194);border-radius: 2px;}")
        self.urllocation.setDragEnabled(False)
        self.urllocation.setReadOnly(True)
        self.urllocation.setObjectName("urllocation")
        self.verticalLayout_2.addWidget(self.urllocation)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_2.addWidget(self.mainwin)
        self.settin = QtWidgets.QGroupBox(self.dialogbox)
        self.settin.setMinimumSize(QtCore.QSize(0, 0))
        self.settin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.settin.setStyleSheet("QWidget{outline: none;show-decoration-selected: 1}\n"
"QGroupBox{border:0px;background-color:#ffffff;border-left: 1px solid #dfe0df;}\n"
"QComboBox{\n"
"background-color:#FCFCFC;\n"
"border: 1px;\n"
"border-style: solid;\n"
"border-color:#c0c4d2;\n"
"border-radius:2px;}\n"
"QComboBox::drop-down {\n"
"subcontrol-origin: padding;\n"
"subcontrol-position: top right;\n"
"width: 20px;\n"
"border-top-right-radius: 3px;\n"
"border-bottom-right-radius: 3px;}\n"
"QComboBox::down-arrow {image: url(:/MainSources/Down.png);}\n"
"QAbstractItemView{border: 2px solid darkgray;selection-background-color: lightgray;font-family:Roboto, \'Segoe UI\', Tahoma, sans-serif;font-size:11px;}\n"
"QSpinBox{background-color:#FCFCFC;border: 1px solid #c0c4d2;border-radius:2px;}\n"
"QSpinBox::up-button {subcontrol-origin: border;\n"
"subcontrol-position: top right;\n"
"border-width: 1px;}\n"
"QSpinBox::up-arrow {\n"
"image: url(:/MainSources/up.png);\n"
"width: 7px;\n"
"height: 7px;}\n"
"QSpinBox::down-arrow {\n"
"image: url(:/MainSources/downn.png);\n"
"width: 7px;\n"
"height: 7px;}\n"
"QSpinBox::down-button {\n"
"subcontrol-origin: border;\n"
"subcontrol-position: bottom right;\n"
"border-width: 1px;}")
        self.settin.setTitle("")
        self.settin.setObjectName("settin")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.settin)
        self.verticalLayout.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.settin)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox{border:0px;}\n"
"QLabel{font-family:Roboto, \'Segoe UI\', Tahoma, sans-serif;}")
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setContentsMargins(-1, 40, -1, -1)
        self.formLayout.setSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.printdes = QtWidgets.QComboBox(self.groupBox)
        self.printdes.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(9)
        self.printdes.setFont(font)
        self.printdes.setStyleSheet("")
        self.printdes.setMaxVisibleItems(15)
        self.printdes.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.printdes.setMinimumContentsLength(30)
        self.printdes.setObjectName("printdes")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.printdes)
        self.printpsize = QtWidgets.QComboBox(self.groupBox)
        self.printpsize.setMinimumSize(QtCore.QSize(0, 30))
        self.printpsize.setObjectName("printpsize")
        self.printpsize.addItem("")
        self.printpsize.addItem("")
        self.printpsize.addItem("")
        self.printpsize.addItem("")
        self.printpsize.addItem("")
        self.printpsize.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.printpsize)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.layoutP = QtWidgets.QComboBox(self.groupBox)
        self.layoutP.setMinimumSize(QtCore.QSize(0, 30))
        self.layoutP.setObjectName("layoutP")
        self.layoutP.addItem("")
        self.layoutP.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.layoutP)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox.setFont(font)
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.printdialog = QtWidgets.QPushButton(self.settin)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.printdialog.setFont(font)
        self.printdialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.printdialog.setStyleSheet("QPushButton {font-family:Roboto, \'Segoe UI\', Tahoma, sans-serif;border:0px;}\n"
"QPushButton::hover {color:#4683ff;border:0px;}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/MainSources/link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.printdialog.setIcon(icon)
        self.printdialog.setDefault(False)
        self.printdialog.setFlat(True)
        self.printdialog.setObjectName("printdialog")
        self.verticalLayout.addWidget(self.printdialog)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.pusprint = QtWidgets.QPushButton(self.settin)
        self.pusprint.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pusprint.setFont(font)
        self.pusprint.setStyleSheet("QPushButton {\n"
"border-radius:5px;\n"
"background-color: #4683ff;\n"
"color: #ffffff;\n"
"font-family:Roboto, \'Segoe UI\', Tahoma, sans-serif;\n"
"padding-left:15px;\n"
"padding-right:15px;}\n"
"QPushButton::hover {background-color:#568dff;}")
        self.pusprint.setObjectName("pusprint")
        self.horizontalLayout_4.addWidget(self.pusprint)
        self.close = QtWidgets.QPushButton(self.settin)
        self.close.setMinimumSize(QtCore.QSize(0, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.close.setFont(font)
        self.close.setStyleSheet("QPushButton {\n"
"border-radius:5px;\n"
"border:1px solid #e6e6e6;\n"
"background-color: #ffffff;\n"
"color: #4683ff;\n"
"font-family:Roboto, \'Segoe UI\', Tahoma, sans-serif;\n"
"padding-left:15px;\n"
"padding-right:15px;}\n"
"QPushButton::hover {background-color:#ecf2ff;}")
        self.close.setObjectName("close")
        self.horizontalLayout_4.addWidget(self.close)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addWidget(self.settin)
        self.horizontalLayout.addWidget(self.dialogbox)

        self.retranslateUi(Dialog)
        self.close.clicked.connect(Dialog.reject)
        self.pusprint.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label5.setText(_translate("Dialog", "جارى المعاينة ...."))
        self.groupBox.setTitle(_translate("Dialog", "Print"))
        self.label.setText(_translate("Dialog", "Destination"))
        self.printpsize.setItemText(0, _translate("Dialog", "A5"))
        self.printpsize.setItemText(1, _translate("Dialog", "Letter"))
        self.printpsize.setItemText(2, _translate("Dialog", "Legal"))
        self.printpsize.setItemText(3, _translate("Dialog", "A4"))
        self.printpsize.setItemText(4, _translate("Dialog", "B5"))
        self.printpsize.setItemText(5, _translate("Dialog", "A6"))
        self.label_2.setText(_translate("Dialog", "Paper Size"))
        self.layoutP.setItemText(0, _translate("Dialog", "Portrait"))
        self.layoutP.setItemText(1, _translate("Dialog", "Landscape"))
        self.label_4.setText(_translate("Dialog", "Layout"))
        self.label_3.setText(_translate("Dialog", "Copies"))
        self.printdialog.setText(_translate("Dialog", "Print using system dialog"))
        self.pusprint.setText(_translate("Dialog", "Print"))
        self.close.setText(_translate("Dialog", "Cancel"))
import sources_rc
